---
- hosts: "{{ host_list }}"
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
  - name: Add ansible user
    user:
      name: ansible
      comment: Ansible User
      uid: 1100
      state: present

  - name: Add authorized key
    authorized_key: 
      user: ansible
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      state: present
